version: '3.7'

services:
  db:
    restart: always
    container_name: mapping_db
    image: postgres:alpine

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    env_file:
      - .env
    volumes:
      - .data/postgresql:/var/lib/postgresql/data


